export interface NovenaContent {
    id: string;
    name: string;
    description: string;
    dayOneText: string;
    dayTwoText: string;
    dayThreeText: string;
    dayFourText: string;
    dayFiveText: string;
    daySixText: string;
    daySevenText: string;
    dayEightText: string;
    dayNineText: string;
}

export const NOVENA_CONTENT: NovenaContent[] = [
    // EXISTING
    {
        id: "novena_jude",
        name: "Novena to St. Jude",
        description: "For desperate situations and hopeless causes.",
        dayOneText: "St. Jude, glorious Apostle, faithful servant and friend of Jesus, the name of the traitor has caused you to be forgotten by many. But the Church honors and invokes you universally as the patron of difficult cases, and of things almost despaired of.",
        dayTwoText: "Pray for me, that I may be given the grace to accept God's holy will even in my moments of greatest need. St. Jude, help of the hopeless, pray for us.",
        dayThreeText: "St. Jude, you witnessed the miracles of Jesus. Help me to trust in His power to heal and restore.",
        dayFourText: "St. Jude, through your intercession, may I find peace in the midst of my trials.",
        dayFiveText: "St. Jude, teach me to be patient and to wait on the Lord with confidence.",
        daySixText: "St. Jude, help me to see the purpose in my suffering and to offer it to God.",
        daySevenText: "St. Jude, obtain for me the strength to persevere in faith, hope, and love.",
        dayEightText: "St. Jude, by your prayers, may I be delivered from all evil and distress.",
        dayNineText: "St. Jude, thank you for your intercession. I promise to make your name known and cause you to be invoked."
    },
    {
        id: "novena_sacred_heart",
        name: "Novena to the Sacred Heart",
        description: "Trust in the infinite love and mercy of Jesus.",
        dayOneText: "O my Jesus, you have said: 'Truly I say to you, ask and you will receive, seek and you will find, knock and it will be opened to you.' Behold I knock, I seek and ask for the grace of...",
        dayTwoText: "O my Jesus, you have said: 'Truly I say to you, anything you ask the Father in my name, he will give it to you.' Behold, in your name, I ask the Father for the grace of...",
        dayThreeText: "O my Jesus, you have said: 'Truly I say to you, Heaven and earth will pass away but my words will not pass away.' Encouraged by your infallible words I now ask for the grace of...",
        dayFourText: "O Sacred Heart of Jesus, for whom it is impossible not to have compassion on the afflicted, have pity on us miserable sinners and grant us the grace which we ask of you.",
        dayFiveText: "Through the Sorrowful and Immaculate Heart of Mary, your tender Mother and ours, I ask for this special favor.",
        daySixText: "O Sacred Heart of Jesus, I place all my trust in you.",
        daySevenText: "O Sacred Heart of Jesus, may your kingdom come.",
        dayEightText: "O Sacred Heart of Jesus, protect our families.",
        dayNineText: "O Sacred Heart of Jesus, I believe in your love for me."
    },
    {
        id: "novena_mercy",
        name: "Divine Mercy Novena",
        description: "Bringing souls to the font of God's mercy.",
        dayOneText: "Today bring to Me all mankind, especially all sinners, and immerse them in the ocean of My mercy.",
        dayTwoText: "Today bring to Me the souls of priests and religious, and immerse them in My unfathomable mercy.",
        dayThreeText: "Today bring to Me all devout and faithful souls, and immerse them in the ocean of My mercy.",
        dayFourText: "Today bring to Me those who do not believe in God and those who do not yet know Me.",
        dayFiveText: "Today bring to Me the souls of those who have separated themselves from My Church.",
        daySixText: "Today bring to Me the meek and humble souls and the souls of little children.",
        daySevenText: "Today bring to Me the souls who especially venerate and glorify My mercy.",
        dayEightText: "Today bring to Me the souls who are detained in purgatory.",
        dayNineText: "Today bring to Me souls who have become lukewarm."
    },
    {
        id: "novena_perpetual_help",
        name: "Our Lady of Perpetual Help",
        description: "Asking for Mary's maternal aid in our daily lives.",
        dayOneText: "O Mother of Perpetual Help, grant that I may ever invoke your powerful name, the protection of the living and the salvation of the dying.",
        dayTwoText: "O Mary, help me to overcome the temptations that surround me.",
        dayThreeText: "O Mother, grant me a love for Jesus Christ that is true and lasting.",
        dayFourText: "O Lady of Perpetual Help, watch over my family and loved ones.",
        dayFiveText: "O Mary, comfort me in my sorrows and strengthen me in my weakness.",
        daySixText: "O Mother, obtain for me the grace of a happy death.",
        daySevenText: "O Lady, help me to be a faithful child of God.",
        dayEightText: "O Mother, I place all my trust in your intercession.",
        dayNineText: "O Mother of Perpetual Help, pray for us who have recourse to thee."
    },
    {
        id: "novena_joseph",
        name: "Novena to St. Joseph",
        description: "Patron of workers, fathers, and a happy death.",
        dayOneText: "St. Joseph, foster father of Jesus, watch over our families as you watched over the Holy Family.",
        dayTwoText: "St. Joseph, patron of workers, help us to find dignity in our labor.",
        dayThreeText: "St. Joseph, terror of demons, protect us from all spiritual attacks.",
        dayFourText: "St. Joseph, model of patience, teach us to wait on the Lord.",
        dayFiveText: "St. Joseph, pillar of families, strengthen our homes.",
        daySixText: "St. Joseph, comfort of the afflicted, pray for those who are suffering.",
        daySevenText: "St. Joseph, hope of the sick, intercede for healing.",
        dayEightText: "St. Joseph, patron of the dying, pray for us at the hour of our death.",
        dayNineText: "St. Joseph, protector of the Holy Church, guide us in truth."
    },

    // NEW ADDITIONS (25+)
    {
        id: "novena_therese",
        name: "St. Thérèse of Lisieux",
        description: "The Little Flower. For simplicity and confidence.",
        dayOneText: "St. Thérèse, privileged Little Flower of Jesus and Mary, I approach you with childlike confidence.",
        dayTwoText: "Teach me to follow your 'Little Way' of trust and self-surrender to God's merciful love.",
        dayThreeText: "help me to believe as you did in God's great love for me, so that I might imitate your 'Little Way'.",
        dayFourText: "Make me precious in the eyes of God, and lift this petition to His throne.",
        dayFiveText: "St. Thérèse, help me to be faithful to God in the little things of everyday life.",
        daySixText: "Shower down your roses of grace upon me, and upon those I love.",
        daySevenText: "I desire to love Jesus and to make Him loved. Help me to do this.",
        dayEightText: "St. Thérèse, patroness of missions, pray for the spread of the Gospel.",
        dayNineText: "I promise to imitate your virtues and to trust God in all things."
    },
    {
        id: "novena_anthony",
        name: "St. Anthony of Padua",
        description: "Patron of lost things and miracles.",
        dayOneText: "St. Anthony, gentle and powerful in your help, I turn to you in my need.",
        dayTwoText: "You who restored sight to the blind and speech to the mute, help me in my present necessity.",
        dayThreeText: "St. Anthony, preacher of grace, help me to find what I have lost (mention request).",
        dayFourText: "Protect me from all confusion of mind and darkness of soul.",
        dayFiveText: "St. Anthony, glory of the Franciscan Order, teach me to love poverty of spirit.",
        daySixText: "Helper of the poor and distressed, intercede for my family.",
        daySevenText: "St. Anthony, Hammer of Heretics, keep me firm in the true faith.",
        dayEightText: "Through your prayers, may I be delivered from all danger.",
        dayNineText: "I thank you, St. Anthony, for your powerful intercession."
    },
    {
        id: "novena_michael",
        name: "St. Michael Archangel",
        description: "For protection against evil.",
        dayOneText: "St. Michael the Archangel, defend us in battle. Be our protection against the wickedness of the devil.",
        dayTwoText: "Prince of the heavenly host, cast into hell Satan and all evil spirits.",
        dayThreeText: "St. Michael, protector of the Church, guard the Holy Father and all clergy.",
        dayFourText: "Help us to be faithful to our baptismal promises and to renounce Satan.",
        dayFiveText: "St. Michael, strength of God, strengthen us in our weakness.",
        daySixText: "Defend us in our last agony and lead our souls to heaven.",
        daySevenText: "St. Michael, advocate of the dying, be with us at the hour of death.",
        dayEightText: "Guardian of Purgatory, pray for the holy souls.",
        dayNineText: "Victory of God, grant us victory over our temptations."
    },
    {
        id: "novena_rita",
        name: "St. Rita of Cascia",
        description: "Patroness of impossible causes.",
        dayOneText: "St. Rita, advocate of the impossible, I come to you with confidence in my great need.",
        dayTwoText: "You who suffered the pain of the thorn, teach me to unite my sufferings to Jesus.",
        dayThreeText: "St. Rita, model of wives and mothers, pray for my family.",
        dayFourText: "Help me to forgive those who have hurt me, as you forgave your enemies.",
        dayFiveText: "St. Rita, obtain for me the grace I so desperately need (mention request).",
        daySixText: "Mirror of patience, help me to bear my cross with love.",
        daySevenText: "St. Rita, lover of peace, bring peace to my heart and home.",
        dayEightText: "Through your intercession, may God grant what seems impossible to us.",
        dayNineText: "I promise to make known your favor and to live a holy life."
    },
    {
        id: "novena_holy_spirit",
        name: "Novena to the Holy Spirit",
        description: "For the seven gifts and guidance.",
        dayOneText: "Come, Holy Spirit, fill the hearts of your faithful and kindle in them the fire of your love.",
        dayTwoText: "Spirit of Wisdom, guide our thoughts and actions.",
        dayThreeText: "Spirit of Understanding, enlighten our minds to know the truth.",
        dayFourText: "Spirit of Counsel, help us to choose what is right.",
        dayFiveText: "Spirit of Fortitude, strengthen us in times of trial.",
        daySixText: "Spirit of Knowledge, help us to see God in all creation.",
        daySevenText: "Spirit of Piety, fill us with reverence for God.",
        dayEightText: "Spirit of Fear of the Lord, keep us from sin.",
        dayNineText: "Come, Holy Spirit, renew the face of the earth."
    },
    {
        id: "novena_padre_pio",
        name: "St. Padre Pio",
        description: "For healing and spiritual guidance.",
        dayOneText: "St. Padre Pio, witness of faith and love, pray for us.",
        dayTwoText: "You who bore the wounds of Christ, help us to accept our sufferings.",
        dayThreeText: "Teach us the value of the Holy Mass and the Rosary.",
        dayFourText: "Padre Pio, help us to be charitable to those in need.",
        dayFiveText: "Protect your spiritual children and lead us to heaven.",
        daySixText: "Healer of bodies and souls, intercede for our healing.",
        daySevenText: "Padre Pio, terror of demons, protect us from the evil one.",
        dayEightText: "Help us to trust in God's providence as you did.",
        dayNineText: "Pray, hope, and don't worry. St. Padre Pio, pray for us."
    },
    {
        id: "novena_peregrine",
        name: "St. Peregrine",
        description: "Patron of cancer patients.",
        dayOneText: "St. Peregrine, you who suffered from cancer, I ask for your help.",
        dayTwoText: "Intercede for (name), who is suffering from this illness.",
        dayThreeText: "St. Peregrine, model of patience, help us to bear this cross.",
        dayFourText: "Ask God to grant healing if it is His holy will.",
        dayFiveText: "Give us strength and courage in this time of trial.",
        daySixText: "St. Peregrine, you were healed by a vision of Jesus crucified, pray for us.",
        daySevenText: "Comfort those who are in pain and distress.",
        dayEightText: "Help us to unite our sufferings with Christ on the Cross.",
        dayNineText: "St. Peregrine, patron of the sick, pray for us."
    },
    {
        id: "novena_monica",
        name: "St. Monica",
        description: "For the conversion of children and patience.",
        dayOneText: "St. Monica, model of patience and prayer, pray for my children.",
        dayTwoText: "You who wept for Augustine, intercede for those who have lost their way.",
        dayThreeText: "Teach me to never give up hope in God's mercy.",
        dayFourText: "St. Monica, protect our families from the influences of the world.",
        dayFiveText: "Grant me the grace of persistence in prayer.",
        daySixText: "St. Monica, help me to lead my family to God by my example.",
        daySevenText: "Intercede for the conversion of sinners in my family.",
        dayEightText: "Comfort all mothers who worry for their children.",
        dayNineText: "St. Monica, pray that we may all be reunited in heaven."
    },
    {
        id: "novena_benedict",
        name: "St. Benedict",
        description: "Against poison and for peace.",
        dayOneText: "St. Benedict, father of Western Monasticism, pray for us.",
        dayTwoText: "Protect us from the snares of the enemy.",
        dayThreeText: "Teach us to pray and work (Ora et Labora).",
        dayFourText: "St. Benedict, guide us in the way of peace.",
        dayFiveText: "Intercede for the renewal of Christian culture.",
        daySixText: "Help us to prefer nothing to the love of Christ.",
        daySevenText: "St. Benedict, terror of evil spirits, drive them far from us.",
        dayEightText: "Grant us the grace of a holy death.",
        dayNineText: "St. Benedict, pray for us."
    },
    {
        id: "novena_francis",
        name: "St. Francis of Assisi",
        description: "For peace and love of nature.",
        dayOneText: "St. Francis, poor man of Assisi, make me an instrument of peace.",
        dayTwoText: "Teach me to love God in all His creation.",
        dayThreeText: "St. Francis, help me to be humble and poor in spirit.",
        dayFourText: "Where there is hatred, let me sow love.",
        dayFiveText: "St. Francis, rebuild God's Church in our hearts.",
        daySixText: "Intercede for peace in the world and in our families.",
        daySevenText: "Help us to find joy in simplicity.",
        dayEightText: "St. Francis, marked with the stigmata, pray for us.",
        dayNineText: "May I love God above all things."
    },
    {
        id: "novena_patrick",
        name: "St. Patrick",
        description: "For faith and protection.",
        dayOneText: "St. Patrick, apostle of Ireland, renew my faith.",
        dayTwoText: "Christ be with me, Christ within me, Christ behind me, Christ before me.",
        dayThreeText: "Protect me against the snares of the enemy.",
        dayFourText: "St. Patrick, teach me the mystery of the Trinity.",
        dayFiveText: "Help me to be a missionary of truth.",
        daySixText: "St. Patrick, grant me courage to speak the Gospel.",
        daySevenText: "Intercede for the people of Ireland and the whole world.",
        dayEightText: "Bind me to the virtues of Christ.",
        dayNineText: "St. Patrick, pray for us."
    },
    {
        id: "novena_anne",
        name: "St. Anne",
        description: "For mothers and grandmothers.",
        dayOneText: "Good St. Anne, mother of Mary, pray for our families.",
        dayTwoText: "You who raised the Mother of God, guide all parents.",
        dayThreeText: "St. Anne, help of the pregnant and childless, intercede for them.",
        dayFourText: "Protect our grandchildren and lead them to Jesus.",
        dayFiveText: "St. Anne, model of piety, teach us to love God.",
        daySixText: "Comfort the elderly and the lonely.",
        daySevenText: "St. Anne, obtain for us the grace of a holy life.",
        dayEightText: "Prepare our hearts to receive Jesus.",
        dayNineText: "St. Anne, pray for us."
    },
    {
        id: "novena_knots",
        name: "Our Lady Undoer of Knots",
        description: "For solving complex problems.",
        dayOneText: "Dearest Holy Mother, you undo the knots that suffocate our souls. I entrust to you (mention knot).",
        dayTwoText: "Mary, Mother of Fair Love, I look to you. Take this knot from my life.",
        dayThreeText: "Mother, by your grace, intercede for me. Undo this knot that causes me pain.",
        dayFourText: "Mother, you who know my sorrow, untie this knot.",
        dayFiveText: "Mother, generous with grace, I come to you today.",
        daySixText: "Queen of Mercy, I give you this knot of my life.",
        daySevenText: "Mother most pure, I come to you to untie this knot.",
        dayEightText: "Mother of God, rich in mercy, look on your child.",
        dayNineText: "Mary, Undoer of Knots, pray for me."
    },
    {
        id: "novena_lourdes",
        name: "Our Lady of Lourdes",
        description: "For healing.",
        dayOneText: "Our Lady of Lourdes, pray for us.",
        dayTwoText: "Healer of the sick, intercede for us.",
        dayThreeText: "Comforter of the afflicted, pray for us.",
        dayFourText: "Immaculate Conception, pray for us.",
        dayFiveText: "Health of the sick, pray for us.",
        daySixText: "Refuge of sinners, pray for us.",
        daySevenText: "Mother of the Church, pray for us.",
        dayEightText: "Queen of Heaven, pray for us.",
        dayNineText: "Our Lady of Lourdes, heal us."
    },
    {
        id: "novena_fatima",
        name: "Our Lady of Fatima",
        description: "For peace and conversion.",
        dayOneText: "Our Lady of Fatima, pray for our country.",
        dayTwoText: "Sanctify our clergy.",
        dayThreeText: "Make our Catholics more fervent.",
        dayFourText: "Guide and inspire those who govern us.",
        dayFiveText: "Cure the sick who confide in thee.",
        daySixText: "Console the sorrowful.",
        daySevenText: "Help those who invoke your aid.",
        dayEightText: "Save us from the fires of hell.",
        dayNineText: "Our Lady of Fatima, pray for us."
    },
    {
        id: "novena_infant",
        name: "Infant Jesus of Prague",
        description: "For urgent financial or family needs.",
        dayOneText: "O Infant Jesus, I have recourse to You.",
        dayTwoText: "I trust that You will help me in this necessity.",
        dayThreeText: "I love You with all my heart.",
        dayFourText: "I am sorry for my sins.",
        dayFiveText: "I give myself seeking Your holy will.",
        daySixText: "I ask You to help me in this need.",
        daySevenText: "Grant me the grace to possess You eternally.",
        dayEightText: "O Divine Infant, bless us.",
        dayNineText: "O Infant Jesus, hear my prayer."
    },
    {
        id: "novena_maximilian",
        name: "St. Maximilian Kolbe",
        description: "For addiction and prisoners.",
        dayOneText: "St. Maximilian, martyr of charity, pray for us.",
        dayTwoText: "You who gave your life for another, teach us to love.",
        dayThreeText: "Patron of the addicted, break our chains.",
        dayFourText: "Lover of the Immaculate, lead us to Mary.",
        dayFiveText: "St. Maximilian, help us in our darkness.",
        daySixText: "Pray for the imprisoned and the oppressed.",
        daySevenText: "Witness of truth, guide us.",
        dayEightText: "Apostle of the media, sanctify our communications.",
        dayNineText: "St. Maximilian, pray for us."
    },
    {
        id: "novena_teresa_calcutta",
        name: "St. Teresa of Calcutta",
        description: "For the poor and service.",
        dayOneText: "St. Teresa, mother of the poor, pray for us.",
        dayTwoText: "Teach us to see Jesus in the distressed disguise of the poor.",
        dayThreeText: "Help us to do small things with great love.",
        dayFourText: "St. Teresa, advocate of life, pray for the unborn.",
        dayFiveText: "Carrier of God's love, fill our hearts.",
        daySixText: "Quench the thirst of Jesus on the Cross.",
        daySevenText: "Smile at Jesus in your suffering.",
        dayEightText: "Pray that we may be holy.",
        dayNineText: "St. Teresa, pray for us."
    },
    {
        id: "novena_jp2",
        name: "St. John Paul II",
        description: "For youth and families.",
        dayOneText: "St. John Paul II, pray for our families.",
        dayTwoText: "Simple servant of the servants of God, pray for us.",
        dayThreeText: "Totus Tuus - teach us to belong to Mary.",
        dayFourText: "Open wide the doors to Christ.",
        dayFiveText: "Be not afraid.",
        daySixText: "Defender of life, pray for the unborn.",
        daySevenText: "Lover of the youth, guide our young people.",
        dayEightText: "Witness of suffering, help us bear our crosses.",
        dayNineText: "St. John Paul II, pray for us."
    },
    {
        id: "novena_philomena",
        name: "St. Philomena",
        description: "Powerful virgin martyr.",
        dayOneText: "St. Philomena, beloved daughter of the Divine Will.",
        dayTwoText: "St. Philomena, to whom nothing is refused.",
        dayThreeText: "St. Philomena, pray for us in our need.",
        dayFourText: "St. Philomena, virgin and martyr.",
        dayFiveText: "St. Philomena, example of purity.",
        daySixText: "St. Philomena, courageous in suffering.",
        daySevenText: "St. Philomena, help of the sick.",
        dayEightText: "St. Philomena, powerful with God.",
        dayNineText: "St. Philomena, pray for us."
    },
    {
        id: "novena_immaculate",
        name: "Immaculate Conception",
        description: "For purity and grace.",
        dayOneText: "O Mary, conceived without sin, pray for us.",
        dayTwoText: "O Mary, full of grace, fill our hearts.",
        dayThreeText: "O Mary, masterpiece of God, guide us.",
        dayFourText: "O Mary, pure and holy, cleanse us.",
        dayFiveText: "O Mary, refuge of sinners, save us.",
        daySixText: "O Mary, Ark of the Covenant, carry us to Jesus.",
        daySevenText: "O Mary, Morning Star, light our way.",
        dayEightText: "O Mary, cause of our joy, bless us.",
        dayNineText: "O Mary, conceived without sin, pray for us who have recourse to thee."
    },
    {
        id: "novena_assumption",
        name: "The Assumption",
        description: "For a holy death and heaven.",
        dayOneText: "Queen assumed into heaven, pray for us.",
        dayTwoText: "Queen of Angels, pray for us.",
        dayThreeText: "Queen of Patriarchs, pray for us.",
        dayFourText: "Queen of Prophets, pray for us.",
        dayFiveText: "Queen of Apostles, pray for us.",
        daySixText: "Queen of Martyrs, pray for us.",
        daySevenText: "Queen of Confessors, pray for us.",
        dayEightText: "Queen of Virgins, pray for us.",
        dayNineText: "Queen of all Saints, pray for us."
    },
    {
        id: "novena_kateri",
        name: "St. Kateri Tekakwitha",
        description: "For ecology and native peoples.",
        dayOneText: "St. Kateri, Lily of the Mohawks, pray for us.",
        dayTwoText: "Lover of the Cross, teach us to love suffering.",
        dayThreeText: "Pure flower of the wilderness, keep us pure.",
        dayFourText: "St. Kateri, friend of nature, help us care for creation.",
        dayFiveText: "St. Kateri, pray for the native peoples.",
        daySixText: "St. Kateri, help the outcast.",
        daySevenText: "St. Kateri, model of virginity.",
        dayEightText: "St. Kateri, pray for the sick.",
        dayNineText: "St. Kateri, pray for us."
    },
    {
        id: "novena_bernadette",
        name: "St. Bernadette",
        description: "For humility and the sick.",
        dayOneText: "St. Bernadette, humble servant, pray for us.",
        dayTwoText: "You who saw the Immaculate, pray for us.",
        dayThreeText: "Model of simplicity, teach us.",
        dayFourText: "Patient in suffering, help us.",
        dayFiveText: "St. Bernadette, pray for the sick.",
        daySixText: "St. Bernadette, pray for the poor.",
        daySevenText: "St. Bernadette, pray for sinners.",
        dayEightText: "St. Bernadette, pray for the church.",
        dayNineText: "St. Bernadette, pray for us."
    },
    {
        id: "novena_charbel",
        name: "St. Charbel",
        description: "Miraculous healer monk.",
        dayOneText: "St. Charbel, hermit of Lebanon, pray for us.",
        dayTwoText: "Miracle worker, heal us.",
        dayThreeText: "Lover of silence, teach us to pray.",
        dayFourText: "Model of fasting, help us.",
        dayFiveText: "Devoted to the Eucharist, increase our faith.",
        daySixText: "St. Charbel, protect our families.",
        daySevenText: "St. Charbel, unite East and West.",
        dayEightText: "St. Charbel, friend of God.",
        dayNineText: "St. Charbel, pray for us."
    },
    {
        id: "novena_lucy",
        name: "St. Lucy",
        description: "For eye ailments.",
        dayOneText: "St. Lucy, whose name means light, pray for us.",
        dayTwoText: "Protect our eyes and our vision.",
        dayThreeText: "Help us to see the truth.",
        dayFourText: "St. Lucy, virgin martyr, pray for purity.",
        dayFiveText: "Guide us in the darkness.",
        daySixText: "St. Lucy, faithful to Christ.",
        daySevenText: "St. Lucy, courageous witness.",
        dayEightText: "Heal those with eye trouble.",
        dayNineText: "St. Lucy, pray for us."
    },
    {
        id: "novena_raphael",
        name: "St. Raphael Archangel",
        description: "For healing and travelers.",
        dayOneText: "St. Raphael, medicine of God, heal us.",
        dayTwoText: "Guide us on our journey.",
        dayThreeText: "Help us find our true vocation.",
        dayFourText: "Protect us from danger.",
        dayFiveText: "Heal our relationships.",
        daySixText: "Companion of Tobias, be our friend.",
        daySevenText: "Angel of happy meetings.",
        dayEightText: "Bring our prayers to God.",
        dayNineText: "St. Raphael, pray for us."
    },
    {
        id: "novena_aquinas",
        name: "St. Thomas Aquinas",
        description: "For students and schools.",
        dayOneText: "St. Thomas, patron of students, pray for us.",
        dayTwoText: "Grant us clarity of mind.",
        dayThreeText: "Help us understand the truth.",
        dayFourText: "Purity of heart, grant us.",
        dayFiveText: "Angelic Doctor, teach us.",
        daySixText: "Help us in our studies.",
        daySevenText: "St. Thomas, light of the Church.",
        dayEightText: "Guide our schools.",
        dayNineText: "St. Thomas, pray for us."
    },
    {
        id: "novena_imp_work",
        name: "Novena for Work",
        description: "For finding employment.",
        dayOneText: "God, my Father, I turn to you seeking work.",
        dayTwoText: "Guide my steps to the right opportunity.",
        dayThreeText: "Help me to be patient and trust in You.",
        dayFourText: "Grant me favor in interviews.",
        dayFiveText: "Provide for my daily needs.",
        daySixText: "Help me to use my talents for Your glory.",
        daySevenText: "Remove my anxiety and fear.",
        dayEightText: "Bless the work of my hands.",
        dayNineText: "Thank You, Father, for Your provision."
    }
];
