import { MetadataRoute } from 'next';

const baseUrl = 'https://myprayertower.com';

export default function sitemap(): MetadataRoute.Sitemap {
    const staticRoutes = [
        '',
        '/about',
        '/actions',
        '/advertise',
        '/anniversaries',
        '/art',
        '/bible',
        '/bouquets',
        '/calendar',
        '/campaigns',
        '/candles',
        '/canon-law',
        '/careers',
        '/catechism',
        '/challenges',
        '/chant',
        '/chaplets',
        '/churches',
        '/claim',
        '/contact',
        '/contributions',
        '/cookies',
        '/dioceses',
        '/dmca',
        '/encyclicals',
        '/events',
        '/examen',
        '/fasting',
        '/features',
        '/for-churches',
        '/glossary',
        '/groups',
        '/guidelines',
        '/hierarchy',
        '/history',
        '/how-we-work',
        '/hymns',
        '/journey',
        '/leaderboard',
        '/library',
        '/login',
        '/mass-offerings',
        '/mass-times',
        '/memorials',
        '/news',
        '/novenas',
        '/partners',
        '/pilgrimages',
        '/podcasts',
        '/prayer-wall',
        '/prayers',
        '/press',
        '/privacy',
        '/quiz',
        '/readings',
        '/refunds',
        '/register',
        '/rosary',
        '/saints',
        '/stations',
        '/summa',
        '/terms',
        '/testimonies',
        '/vatican-ii',
        '/welcome',
        '/year-in-review',
    ];

    const routes = staticRoutes.map((route) => ({
        url: `${baseUrl}${route}`,
        lastModified: new Date(),
        changeFrequency: 'daily' as const,
        priority: route === '' ? 1 : 0.8,
    }));

    return routes;
}
