/// <reference types="node" />
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ============================================================================
// ALL 385 CATEGORIES FROM MYPRAYERTOWER.COM
// ============================================================================
const allCategories = [
    { name: 'Academic Meeting or Event Prayers', slug: 'academic-meeting-or-event-prayers', count: 9 },
    { name: 'Acts of Prayers', slug: 'acts-of-prayers', count: 113 },
    { name: 'Advent Prayers', slug: 'advent-prayers', count: 13 },
    { name: 'Aging', slug: 'aging', count: 6 },
    { name: 'Angel Prayers', slug: 'angel-prayers', count: 34 },
    { name: 'Arrow Prayers', slug: 'arrow-prayers', count: 6 },
    { name: 'Ash Wednesday Prayers', slug: 'ash-wednesday-prayers', count: 18 },
    { name: 'Babies Prayers', slug: 'babies-prayers', count: 3 },
    { name: 'Baptism Prayers', slug: 'baptism-prayers', count: 2 },
    { name: 'Basic Prayers', slug: 'basic-prayers', count: 129 },
    { name: 'Bedtime Prayers', slug: 'bedtime-prayers', count: 19 },
    { name: 'Biblical Prayers', slug: 'biblical-prayers', count: 46 },
    { name: 'Birth of a Baby', slug: 'birth-of-a-baby', count: 7 },
    { name: 'Birthday Prayers', slug: 'birthday-prayers', count: 2 },
    { name: 'Business Prayers', slug: 'business-prayers', count: 5 },
    { name: 'Calmness', slug: 'calmness', count: 13 },
    { name: 'Care, Companionship, & Fraternity', slug: 'care-companionship-fraternity', count: 9 },
    { name: 'Career Prayers', slug: 'career-prayers', count: 3 },
    { name: 'Child/Parenting', slug: 'child-parenting', count: 4 },
    { name: 'Children Prayers', slug: 'children-prayers', count: 16 },
    { name: 'Christ Prayers', slug: 'christ-prayers', count: 11 },
    { name: 'Christmas Prayers', slug: 'christmas-prayers', count: 17 },
    { name: 'Communion Prayers', slug: 'communion-prayers', count: 49 },
    { name: 'Condolence, Loss, and Sympathy Prayers', slug: 'condolence-loss-and-sympathy-prayers', count: 3 },
    { name: 'Confession Prayers', slug: 'confession-prayers', count: 8 },
    { name: 'Congregation of the Blessed Sacrament Prayers', slug: 'congregation-of-the-blessed-sacrament-prayers', count: 7 },
    { name: 'Consolation Prayers', slug: 'consolation-prayers', count: 1 },
    { name: 'Coronavirus Prayers', slug: 'coronavirus-prayers', count: 33 },
    { name: 'Creation', slug: 'creation', count: 3 },
    { name: 'Danger Prayers', slug: 'danger-prayers', count: 4 },
    { name: 'Democracy Prayers', slug: 'democracy-prayers', count: 3 },
    { name: 'Devotion Prayers', slug: 'devotion-prayers', count: 11 },
    { name: 'Disasters Prayers', slug: 'disasters-prayers', count: 1 },
    { name: 'Discernment Prayers', slug: 'discernment-prayers', count: 7 },
    { name: 'Divinity Prayers', slug: 'divinity-prayers', count: 9 },
    { name: 'Dying Prayers', slug: 'dying-prayers', count: 44 },
    { name: 'Easter Prayers', slug: 'easter-prayers', count: 12 },
    { name: 'en Español Prayers', slug: 'en-espanol-prayers', count: 89 },
    { name: 'Environment and Sustainability Prayers', slug: 'environment-and-sustainability-prayers', count: 9 },
    { name: 'Evening and Bedtime Prayers', slug: 'evening-and-bedtime-prayers', count: 4 },
    { name: 'Evening Prayers', slug: 'evening-prayers', count: 24 },
    { name: 'Faith Prayers', slug: 'faith-prayers', count: 32 },
    { name: 'Family Prayers', slug: 'family-prayers', count: 62 },
    { name: 'Fathers Prayers', slug: 'fathers-prayers', count: 5 },
    { name: 'Fireman Prayers', slug: 'fireman-prayers', count: 4 },
    { name: 'Forgiveness Prayers', slug: 'forgiveness-prayers', count: 4 },
    { name: 'Funeral Prayers', slug: 'funeral-prayers', count: 5 },
    { name: 'General Prayers', slug: 'general-prayers', count: 7 },
    { name: 'God Prayers', slug: 'god-prayers', count: 35 },
    { name: "God's Love Prayers", slug: 'gods-love-prayers', count: 7 },
    { name: 'Grace Prayers', slug: 'grace-prayers', count: 4 },
    { name: 'Graduation and Graduate Prayers', slug: 'graduation-and-graduate-prayers', count: 7 },
    { name: 'Gratitude Prayers', slug: 'gratitude-prayers', count: 3 },
    { name: 'Guardian Angel Prayers', slug: 'guardian-angel-prayers', count: 27 },
    { name: 'Guidance Prayers', slug: 'guidance-prayers', count: 7 },
    { name: 'Haiku Prayers', slug: 'haiku-prayers', count: 17 },
    { name: 'Healing Prayers', slug: 'healing-prayers', count: 36 },
    { name: 'Holiday Prayers', slug: 'holiday-prayers', count: 9 },
    { name: 'Holiness Prayers', slug: 'holiness-prayers', count: 2 },
    { name: 'Home Prayers', slug: 'home-prayers', count: 1 },
    { name: 'Hope Prayers', slug: 'hope-prayers', count: 42 },
    { name: 'Humility Prayers', slug: 'humility-prayers', count: 6 },
    { name: 'Immigrants and Refugees Prayers', slug: 'immigrants-and-refugees-prayers', count: 5 },
    { name: 'Inspiration Prayers', slug: 'inspiration-prayers', count: 1 },
    { name: 'Intercession Prayers', slug: 'intercession-prayers', count: 8 },
    { name: 'Invocation Prayers', slug: 'invocation-prayers', count: 16 },
    { name: 'Jesus Christ Prayers', slug: 'jesus-christ-prayers', count: 86 },
    { name: 'Justice Prayers', slug: 'justice-prayers', count: 8 },
    { name: 'Leadership Prayers', slug: 'leadership-prayers', count: 6 },
    { name: 'Life Prayers', slug: 'life-prayers', count: 15 },
    { name: 'Litanies Prayers', slug: 'litanies-prayers', count: 15 },
    { name: 'Love And Care Prayers', slug: 'love-and-care-prayers', count: 6 },
    { name: 'Love Prayers', slug: 'love-prayers', count: 13 },
    { name: 'Marian (Mary) Prayers', slug: 'marian-mary-prayers', count: 177 },
    { name: 'Marriage Prayers', slug: 'marriage-prayers', count: 4 },
    { name: 'Martyrs Prayers', slug: 'martyrs-prayers', count: 3 },
    { name: 'Mass Prayers', slug: 'mass-prayers', count: 37 },
    { name: 'Meals Prayers', slug: 'meals-prayers', count: 8 },
    { name: 'Mealtime', slug: 'mealtime', count: 28 },
    { name: 'Morning Prayers', slug: 'morning-prayers', count: 23 },
    { name: 'Motherhood Prayers', slug: 'motherhood-prayers', count: 5 },
    { name: 'Network Gathering Prayers', slug: 'network-gathering-prayers', count: 3 },
    { name: 'Offering Prayers', slug: 'offering-prayers', count: 11 },
    { name: 'Opening Meeting Prayers', slug: 'opening-meeting-prayers', count: 4 },
    { name: 'Other Prayers', slug: 'other-prayers', count: 83 },
    { name: 'Peace Prayers', slug: 'peace-prayers', count: 24 },
    { name: 'Perseverance Prayers', slug: 'perseverance-prayers', count: 7 },
    { name: 'Pope Francis I Prayers', slug: 'pope-francis-i-prayers', count: 1 },
    { name: 'Pope Leo XIII Prayers', slug: 'pope-leo-xiii-prayers', count: 3 },
    { name: 'Pope Pius XII Prayers', slug: 'pope-pius-xii-prayers', count: 16 },
    { name: 'Pope Prayers', slug: 'pope-prayers', count: 15 },
    { name: 'Praise Prayers', slug: 'praise-prayers', count: 13 },
    { name: 'Prayer for Abortion', slug: 'prayer-for-abortion', count: 9 },
    { name: 'Prayer for Accountability', slug: 'prayer-for-accountability', count: 5 },
    { name: 'Prayer for Alcoholics', slug: 'prayer-for-alcoholics', count: 17 },
    { name: 'Prayer for Courage', slug: 'prayer-for-courage', count: 6 },
    { name: 'Prayer for Court Cases', slug: 'prayer-for-court-cases', count: 5 },
    { name: 'Prayer for Depression', slug: 'prayer-for-depression', count: 5 },
    { name: 'Prayer for Disappointments', slug: 'prayer-for-disappointments', count: 4 },
    { name: 'Prayer for Fears', slug: 'prayer-for-fears', count: 5 },
    { name: 'Prayer for Husbands', slug: 'prayer-for-husbands', count: 5 },
    { name: 'Prayer for Integrity', slug: 'prayer-for-integrity', count: 5 },
    { name: 'Prayer for My Family', slug: 'prayer-for-my-family', count: 7 },
    { name: 'Prayer for Orphans', slug: 'prayer-for-orphans', count: 5 },
    { name: 'Prayer for Purity', slug: 'prayer-for-purity', count: 6 },
    { name: 'Prayer for the Fruit of the Spirit', slug: 'prayer-for-the-fruit-of-the-spirit', count: 6 },
    { name: 'Prayers', slug: 'prayers', count: 1960 },
    { name: 'Prayers about Fellowship', slug: 'prayers-about-fellowship', count: 16 },
    { name: 'Prayers about Gambling', slug: 'prayers-about-gambling', count: 9 },
    { name: 'Prayers about Jesus', slug: 'prayers-about-jesus', count: 5 },
    { name: 'Prayers about Money', slug: 'prayers-about-money', count: 7 },
    { name: 'Prayers about Spiritual Gifts', slug: 'prayers-about-spiritual-gifts', count: 5 },
    { name: 'Prayers about Temptation', slug: 'prayers-about-temptation', count: 5 },
    { name: 'Prayers about the Birth of Jesus', slug: 'prayers-about-the-birth-of-jesus', count: 5 },
    { name: 'Prayers about the Death of Jesus', slug: 'prayers-about-the-death-of-jesus', count: 5 },
    { name: 'Prayers about the Glory of God', slug: 'prayers-about-the-glory-of-god', count: 9 },
    { name: 'Prayers about the Love of God', slug: 'prayers-about-the-love-of-god', count: 7 },
    { name: 'Prayers Against Strongholds', slug: 'prayers-against-strongholds', count: 5 },
    { name: 'Prayers as Blessings Prayers', slug: 'prayers-as-blessings-prayers', count: 44 },
    { name: 'Prayers before reading the Bible', slug: 'prayers-before-reading-the-bible', count: 5 },
    { name: 'Prayers by Children', slug: 'prayers-by-children', count: 1 },
    { name: 'Prayers by Pope John Paul II', slug: 'prayers-by-pope-john-paul-ii-prayers', count: 4 },
    { name: 'Prayers by St. Francis de Sales', slug: 'prayers-by-st-francis-de-sales-prayers', count: 4 },
    { name: 'Prayers for a Broken Heart', slug: 'prayers-for-a-broken-heart', count: 4 },
    { name: 'Prayers for a New Baby', slug: 'prayers-for-a-new-baby', count: 1 },
    { name: 'Prayers for a New Job', slug: 'prayers-for-a-new-job', count: 9 },
    { name: 'Prayers for a Peace of Mind', slug: 'prayers-for-a-peace-of-mind', count: 6 },
    { name: 'Prayers for a Sick Child', slug: 'prayers-for-a-sick-child', count: 5 },
    { name: 'Prayers for Addiction', slug: 'prayers-for-addiction', count: 5 },
    { name: 'Prayers for Adultery', slug: 'prayers-for-adultery', count: 14 },
    { name: 'Prayers for Advent', slug: 'prayers-for-advent', count: 5 },
    { name: 'Prayers for America', slug: 'prayers-for-america', count: 5 },
    { name: 'Prayers for Anger', slug: 'prayers-for-anger', count: 5 },
    { name: 'Prayers for Anniversaries', slug: 'prayers-for-anniversaries', count: 8 },
    { name: 'Prayers for Anxiety', slug: 'prayers-for-anxiety', count: 5 },
    { name: 'Prayers for Arthritis', slug: 'prayers-for-arthritis', count: 5 },
    { name: 'Prayers for Babies', slug: 'prayers-for-babies', count: 17 },
    { name: 'Prayers for Baptism', slug: 'prayers-for-baptism', count: 2 },
    { name: 'Prayers for Birthdays', slug: 'prayers-for-birthdays', count: 5 },
    { name: 'Prayers for Brothers', slug: 'prayers-for-brothers', count: 5 },
    { name: 'Prayers for Cancer', slug: 'prayers-for-cancer', count: 10 },
    { name: 'Prayers for Change', slug: 'prayers-for-change', count: 5 },
    { name: 'Prayers for Children', slug: 'prayers-for-children', count: 9 },
    { name: 'Prayers for Christmas', slug: 'prayers-for-christmas', count: 4 },
    { name: 'Prayers for Cleansing', slug: 'prayers-for-cleansing', count: 8 },
    { name: 'Prayers for Comfort', slug: 'prayers-for-comfort', count: 10 },
    { name: 'Prayers for Communion', slug: 'prayers-for-communion', count: 9 },
    { name: 'Prayers for Daughters', slug: 'prayers-for-daughters', count: 19 },
    { name: 'Prayers for Death', slug: 'prayers-for-death', count: 7 },
    { name: 'Prayers for Debt Relief', slug: 'prayers-for-debt-relief', count: 5 },
    { name: 'Prayers for Deliverance', slug: 'prayers-for-deliverance', count: 6 },
    { name: 'Prayers for Despair', slug: 'prayers-for-despair', count: 12 },
    { name: 'Prayers for Dinner', slug: 'prayers-for-dinner', count: 5 },
    { name: 'Prayers for Direction', slug: 'prayers-for-direction', count: 8 },
    { name: 'Prayers for Discernment', slug: 'prayers-for-discernment', count: 10 },
    { name: 'Prayers for Diversity', slug: 'prayers-for-diversity', count: 7 },
    { name: 'Prayers for Divorce', slug: 'prayers-for-divorce', count: 6 },
    { name: 'Prayers for Drugs', slug: 'prayers-for-drugs', count: 13 },
    { name: 'Prayers for Emotional Healing', slug: 'prayers-for-emotional-healing', count: 6 },
    { name: 'Prayers for Encouragement', slug: 'prayers-for-encouragement', count: 6 },
    { name: 'Prayers for Engagements', slug: 'prayers-for-engagements', count: 8 },
    { name: 'Prayers for Exams', slug: 'prayers-for-exams', count: 7 },
    { name: 'Prayers for Faith', slug: 'prayers-for-faith', count: 4 },
    { name: 'Prayers for Fathers', slug: 'prayers-for-fathers', count: 4 },
    { name: 'Prayers for Fertility', slug: 'prayers-for-fertility', count: 10 },
    { name: 'Prayers for Fiancés', slug: 'prayers-for-fiances', count: 1 },
    { name: 'Prayers for Financial Help', slug: 'prayers-for-financial-help', count: 11 },
    { name: 'Prayers for Focus', slug: 'prayers-for-focus', count: 15 },
    { name: 'Prayers for Forgiveness', slug: 'prayers-for-forgiveness', count: 17 },
    { name: 'Prayers for Freedom', slug: 'prayers-for-freedom', count: 4 },
    { name: 'Prayers for Friends', slug: 'prayers-for-friends', count: 12 },
    { name: 'Prayers for Fruitfulness', slug: 'prayers-for-fruitfulness', count: 17 },
    { name: 'Prayers for Future Husband', slug: 'prayers-for-future-husband', count: 1 },
    { name: 'Prayers for Giving', slug: 'prayers-for-giving', count: 6 },
    { name: 'Prayers for Gluttony', slug: 'prayers-for-gluttony', count: 7 },
    { name: 'Prayers for Grace', slug: 'prayers-for-grace', count: 27 },
    { name: 'Prayers for Graduation', slug: 'prayers-for-graduation', count: 4 },
    { name: 'Prayers for Grandchildren', slug: 'prayers-for-grandchildren', count: 4 },
    { name: 'Prayers for Grandmothers', slug: 'prayers-for-grandmothers', count: 5 },
    { name: 'Prayers for Grandparents', slug: 'prayers-for-grandparents', count: 5 },
    { name: 'Prayers for Gratitude', slug: 'prayers-for-gratitude', count: 18 },
    { name: 'Prayers for Grief', slug: 'prayers-for-grief', count: 5 },
    { name: 'Prayers for Guidance', slug: 'prayers-for-guidance', count: 6 },
    { name: 'Prayers for Hard Times', slug: 'prayers-for-hard-times', count: 4 },
    { name: 'Prayers for Healing', slug: 'prayers-for-healing', count: 10 },
    { name: 'Prayers for Health', slug: 'prayers-for-health', count: 5 },
    { name: 'Prayers for Help', slug: 'prayers-for-help', count: 4 },
    { name: 'Prayers for Holidays', slug: 'prayers-for-holidays', count: 15 },
    { name: 'Prayers for Holiness', slug: 'prayers-for-holiness', count: 5 },
    { name: 'Prayers for Homeschooling', slug: 'prayers-for-homeschooling', count: 4 },
    { name: 'Prayers for Hope', slug: 'prayers-for-hope', count: 5 },
    { name: 'Prayers for Hospital Patients', slug: 'prayers-for-hospital-patients', count: 5 },
    { name: 'Prayers for Humility', slug: 'prayers-for-humility', count: 12 },
    { name: 'Prayers for illumination', slug: 'prayers-for-illumination', count: 7 },
    { name: 'Prayers for Intercessors', slug: 'prayers-for-intercessors', count: 6 },
    { name: 'Prayers for Israel', slug: 'prayers-for-israel', count: 5 },
    { name: 'Prayers for Jealousy', slug: 'prayers-for-jealousy', count: 4 },
    { name: 'Prayers for Job Interviews', slug: 'prayers-for-job-interviews', count: 5 },
    { name: 'Prayers for Joy', slug: 'prayers-for-joy', count: 17 },
    { name: 'Prayers for Justice', slug: 'prayers-for-justice', count: 4 },
    { name: 'Prayers for Knowing Jesus More', slug: 'prayers-for-knowing-jesus-more', count: 5 },
    { name: 'Prayers for Knowledge', slug: 'prayers-for-knowledge', count: 12 },
    { name: 'Prayers for Leaders', slug: 'prayers-for-leaders', count: 5 },
    { name: 'Prayers for Leaders of the Nations', slug: 'prayers-for-leaders-of-the-nations', count: 7 },
    { name: 'Prayers for Letting Go', slug: 'prayers-for-letting-go', count: 10 },
    { name: 'Prayers for Life', slug: 'prayers-for-life', count: 6 },
    { name: 'Prayers for Loneliness', slug: 'prayers-for-loneliness', count: 11 },
    { name: 'Prayers for Loss', slug: 'prayers-for-loss', count: 28 },
    { name: 'Prayers for Love', slug: 'prayers-for-love', count: 10 },
    { name: 'Prayers for Marriage', slug: 'prayers-for-marriage', count: 6 },
    { name: 'Prayers for Memory Loss', slug: 'prayers-for-memory-loss', count: 8 },
    { name: 'Prayers for Men', slug: 'prayers-for-men', count: 3 },
    { name: 'Prayers for Mercy', slug: 'prayers-for-mercy', count: 5 },
    { name: 'Prayers for Ministry', slug: 'prayers-for-ministry', count: 5 },
    { name: 'Prayers for Mothers', slug: 'prayers-for-mothers', count: 18 },
    { name: 'Prayers for My Boyfriend', slug: 'prayers-for-my-boyfriend', count: 4 },
    { name: 'Prayers for My Current Job', slug: 'prayers-for-my-current-job', count: 8 },
    { name: 'Prayers for My Enemies', slug: 'prayers-for-my-enemies', count: 3 },
    { name: 'Prayers for My Girlfriend', slug: 'prayers-for-my-girlfriend', count: 4 },
    { name: 'Prayers for My Son', slug: 'prayers-for-my-son', count: 6 },
    { name: 'Prayers for my Visa', slug: 'prayers-for-my-visa', count: 8 },
    { name: 'Prayers for My Work Colleagues', slug: 'prayers-for-my-work-colleagues', count: 9 },
    { name: 'Prayers for New Beginnings', slug: 'prayers-for-new-beginnings', count: 8 },
    { name: 'Prayers for New Homes', slug: 'prayers-for-new-homes', count: 1 },
    { name: 'Prayers for Newlyweds', slug: 'prayers-for-newlyweds', count: 5 },
    { name: 'Prayers for Nurses', slug: 'prayers-for-nurses', count: 5 },
    { name: 'Prayers for Obedience', slug: 'prayers-for-obedience', count: 7 },
    { name: 'Prayers for Opening The Year', slug: 'prayers-for-opening-the-year', count: 6 },
    { name: 'Prayers for Our Country', slug: 'prayers-for-our-country', count: 5 },
    { name: 'Prayers for Overcoming', slug: 'prayers-for-overcoming', count: 4 },
    { name: 'Prayers for Parents', slug: 'prayers-for-parents', count: 6 },
    { name: 'Prayers for Pastors', slug: 'prayers-for-pastors', count: 5 },
    { name: 'Prayers for Patience', slug: 'prayers-for-patience', count: 4 },
    { name: 'Prayers for Peace', slug: 'prayers-for-peace', count: 44 },
    { name: 'Prayers for Peace in the Middle East', slug: 'prayers-for-peace-in-the-middle-east', count: 15 },
    { name: 'Prayers for People', slug: 'prayers-for-people', count: 4 },
    { name: 'Prayers for Perseverance', slug: 'prayers-for-perseverance', count: 10 },
    { name: 'Prayers for Pornography', slug: 'prayers-for-pornography', count: 5 },
    { name: 'Prayers for Pregnancy', slug: 'prayers-for-pregnancy', count: 5 },
    { name: 'Prayers for Prisoners', slug: 'prayers-for-prisoners', count: 5 },
    { name: 'Prayers for Protection', slug: 'prayers-for-protection', count: 18 },
    { name: 'Prayers for Provision', slug: 'prayers-for-provision', count: 5 },
    { name: 'Prayers for Purpose', slug: 'prayers-for-purpose', count: 4 },
    { name: 'Prayers for Quitting Smoking', slug: 'prayers-for-quitting-smoking', count: 4 },
    { name: 'Prayers for Racial Justice and Reconciliation', slug: 'prayers-for-racial-justice-and-reconciliation', count: 8 },
    { name: 'Prayers for Rain', slug: 'prayers-for-rain', count: 5 },
    { name: 'Prayers for Reconciliation', slug: 'prayers-for-reconciliation', count: 5 },
    { name: 'Prayers for Recovery', slug: 'prayers-for-recovery', count: 5 },
    { name: 'Prayers for Redemption', slug: 'prayers-for-redemption', count: 5 },
    { name: 'Prayers for Repentance in the Church', slug: 'prayers-for-repentance-in-the-church', count: 5 },
    { name: 'Prayers for Restoration', slug: 'prayers-for-restoration', count: 6 },
    { name: 'Prayers for Retirement', slug: 'prayers-for-retirement', count: 4 },
    { name: 'Prayers for Safety', slug: 'prayers-for-safety', count: 4 },
    { name: 'Prayers for Salvation', slug: 'prayers-for-salvation', count: 9 },
    { name: 'Prayers for Scholarships', slug: 'prayers-for-scholarships', count: 5 },
    { name: 'Prayers for School', slug: 'prayers-for-school', count: 5 },
    { name: 'Prayers for Sickness', slug: 'prayers-for-sickness', count: 8 },
    { name: 'Prayers for Singleness', slug: 'prayers-for-singleness', count: 5 },
    { name: 'Prayers for Singles', slug: 'prayers-for-singles', count: 5 },
    { name: 'Prayers for Sisters', slug: 'prayers-for-sisters', count: 5 },
    { name: 'Prayers for Sleep', slug: 'prayers-for-sleep', count: 6 },
    { name: 'Prayers for Spiritual Growth', slug: 'prayers-for-spiritual-growth', count: 7 },
    { name: 'Prayers for Spiritual Revival', slug: 'prayers-for-spiritual-revival', count: 5 },
    { name: 'Prayers for Spiritual Warfare', slug: 'prayers-for-spiritual-warfare', count: 5 },
    { name: 'Prayers for Strength', slug: 'prayers-for-strength', count: 17 },
    { name: 'Prayers for Stress', slug: 'prayers-for-stress', count: 12 },
    { name: 'Prayers for Students', slug: 'prayers-for-students', count: 5 },
    { name: 'Prayers For Studying and Exams', slug: 'prayers-for-studying-and-exams', count: 7 },
    { name: 'Prayers for Success', slug: 'prayers-for-success', count: 14 },
    { name: 'Prayers for Surgery', slug: 'prayers-for-surgery', count: 5 },
    { name: 'Prayers for Teachers', slug: 'prayers-for-teachers', count: 3 },
    { name: 'Prayers for Teens', slug: 'prayers-for-teens', count: 5 },
    { name: 'Prayers for Thankfulness', slug: 'prayers-for-thankfulness', count: 6 },
    { name: 'Prayers for Thanksgiving', slug: 'prayers-for-thanksgiving', count: 3 },
    { name: 'Prayers for the Dying', slug: 'prayers-for-the-dying', count: 5 },
    { name: 'Prayers for the Elderly', slug: 'prayers-for-the-elderly', count: 5 },
    { name: 'Prayers for the End of Hunger', slug: 'prayers-for-the-end-of-hunger', count: 4 },
    { name: 'Prayers for the First Day of School', slug: 'prayers-for-the-first-day-of-school', count: 6 },
    { name: 'Prayers for the Future', slug: 'prayers-for-the-future', count: 9 },
    { name: 'Prayers for the Home', slug: 'prayers-for-the-home', count: 8 },
    { name: 'Prayers for the Ignatian Year', slug: 'prayers-for-the-ignatian-year', count: 3 },
    { name: 'Prayers for the Military', slug: 'prayers-for-the-military', count: 5 },
    { name: 'Prayers for the Nations', slug: 'prayers-for-the-nations', count: 4 },
    { name: 'Prayers for the Offering', slug: 'prayers-for-the-offering', count: 5 },
    { name: 'Prayers for the Persecuted', slug: 'prayers-for-the-persecuted', count: 6 },
    { name: 'Prayers for the Pope', slug: 'prayers-for-the-pope-prayers', count: 2 },
    { name: 'Prayers for the Suffering', slug: 'prayers-for-the-suffering', count: 5 },
    { name: 'Prayers For Those Who Serve and Protect', slug: 'prayers-for-those-who-serve-and-protect', count: 13 },
    { name: 'Prayers for those Without Work', slug: 'prayers-for-those-without-work', count: 2 },
    { name: 'Prayers for Today', slug: 'prayers-for-today', count: 7 },
    { name: 'Prayers for Transitions and New Beginnings', slug: 'prayers-for-transitions-and-new-beginnings', count: 6 },
    { name: 'Prayers for Travel', slug: 'prayers-for-travel', count: 4 },
    { name: 'Prayers for Trust', slug: 'prayers-for-trust', count: 5 },
    { name: 'Prayers for Truth', slug: 'prayers-for-truth', count: 4 },
    { name: 'Prayers for Unbelievers', slug: 'prayers-for-unbelievers', count: 6 },
    { name: 'Prayers for Unborn Babies', slug: 'prayers-for-unborn-babies', count: 4 },
    { name: 'Prayers for Understanding', slug: 'prayers-for-understanding', count: 7 },
    { name: 'Prayers for Unexpected Deaths', slug: 'prayers-for-unexpected-deaths', count: 5 },
    { name: 'Prayers for Unity in the Church', slug: 'prayers-for-unity-in-the-church', count: 10 },
    { name: 'Prayers for Unsaved Husbands', slug: 'prayers-for-unsaved-husbands', count: 5 },
    { name: 'Prayers for Unsaved Wives', slug: 'prayers-for-unsaved-wives', count: 4 },
    { name: 'Prayers for Uplifting Others', slug: 'prayers-for-uplifting-others', count: 4 },
    { name: 'Prayers for Vacations', slug: 'prayers-for-vacations', count: 5 },
    { name: 'Prayers for Veterans', slug: 'prayers-for-veterans', count: 2 },
    { name: 'Prayers for Victory', slug: 'prayers-for-victory', count: 8 },
    { name: 'Prayers for Vision', slug: 'prayers-for-vision', count: 7 },
    { name: 'Prayers for Vocations', slug: 'prayers-for-vocations', count: 5 },
    { name: 'Prayers for Volunteers', slug: 'prayers-for-volunteers', count: 5 },
    { name: 'Prayers for Waiting on God', slug: 'prayers-for-waiting-on-god', count: 5 },
    { name: 'Prayers for Wealth', slug: 'prayers-for-wealth', count: 5 },
    { name: 'Prayers for Weddings', slug: 'prayers-for-weddings', count: 4 },
    { name: 'Prayers for Weight Loss', slug: 'prayers-for-weight-loss', count: 4 },
    { name: 'Prayers for Wisdom', slug: 'prayers-for-wisdom', count: 9 },
    { name: 'Prayers for Wives', slug: 'prayers-for-wives', count: 5 },
    { name: 'Prayers for Women', slug: 'prayers-for-women', count: 4 },
    { name: 'Prayers for Work', slug: 'prayers-for-work', count: 6 },
    { name: 'Prayers for World Peace', slug: 'prayers-for-world-peace', count: 3 },
    { name: 'Prayers for Worry', slug: 'prayers-for-worry', count: 7 },
    { name: 'Prayers for Worship', slug: 'prayers-for-worship', count: 5 },
    { name: 'Prayers for Youth', slug: 'prayers-for-youth', count: 5 },
    { name: 'Prayers for Youth Groups', slug: 'prayers-for-youth-groups', count: 5 },
    { name: 'Prayers in French', slug: 'prayers-in-french-prayers', count: 10 },
    { name: 'Prayers in German', slug: 'prayers-in-german-prayers', count: 8 },
    { name: 'Prayers in Latin', slug: 'prayers-in-latin-prayers', count: 14 },
    { name: 'Prayers in Spanish', slug: 'prayers-in-spanish-prayers', count: 5 },
    { name: 'Prayers In Times of Natural Disasters', slug: 'prayers-in-times-of-natural-disasters', count: 12 },
    { name: 'Prayers in Times of Terrorism', slug: 'prayers-in-times-of-terrorism', count: 4 },
    { name: 'Prayers of Blessings', slug: 'prayers-of-blessings', count: 11 },
    { name: 'Prayers of Intercession', slug: 'prayers-of-intercession', count: 5 },
    { name: 'Prayers of Repentance', slug: 'prayers-of-repentance', count: 1 },
    { name: 'Prayers of the Church', slug: 'prayers-of-the-church-prayers', count: 10 },
    { name: 'Prayers of the Cross', slug: 'prayers-of-the-cross-prayers', count: 9 },
    { name: 'Prayers on Abiding in Christ', slug: 'prayers-on-abiding-in-christ', count: 5 },
    { name: 'Prayers on Confession', slug: 'prayers-on-confession', count: 7 },
    { name: 'Prayers on Learning How to Pray', slug: 'prayers-on-learning-how-to-pray', count: 5 },
    { name: 'Prayers on Surrender', slug: 'prayers-on-surrender', count: 8 },
    { name: 'Prayers on Unity', slug: 'prayers-on-unity', count: 5 },
    { name: 'Prayers to be in the will of God', slug: 'prayers-to-be-in-the-will-of-god', count: 6 },
    { name: 'Prayers to Sell Your House', slug: 'prayers-to-sell-your-house', count: 10 },
    { name: 'Prayers to the Holy Spirit', slug: 'prayers-to-the-holy-spirit', count: 14 },
    { name: 'Prayers When Confused', slug: 'prayers-when-confused', count: 4 },
    { name: 'Pregnancy Prayers', slug: 'pregnancy-prayers', count: 8 },
    { name: 'Priests Prayers', slug: 'priests-prayers', count: 10 },
    { name: 'Pro Life Prayers', slug: 'pro-life-prayers', count: 3 },
    { name: 'Prosperity Prayers', slug: 'prosperity-prayers', count: 5 },
    { name: 'Protection Prayers', slug: 'protection-prayers', count: 17 },
    { name: 'Purgatory Prayers', slug: 'purgatory-prayers', count: 13 },
    { name: 'Relationship Prayers', slug: 'relationship-prayers', count: 5 },
    { name: 'Repentance Prayers', slug: 'repentance-prayers', count: 8 },
    { name: 'Requests Prayers', slug: 'requests-prayers', count: 4 },
    { name: 'Retirement', slug: 'retirement', count: 4 },
    { name: 'Saint Prayers', slug: 'saint-prayers', count: 120 },
    { name: 'Salvation Prayers', slug: 'salvation-prayers', count: 6 },
    { name: 'Serenity Prayers', slug: 'serenity-prayers', count: 6 },
    { name: 'Service Prayers', slug: 'service-prayers', count: 11 },
    { name: 'Sick Prayers', slug: 'sick-prayers', count: 25 },
    { name: 'Simple Prayers', slug: 'simple-prayers', count: 10 },
    { name: 'Soldiers Prayers', slug: 'soldiers-prayers', count: 5 },
    { name: 'Special Intentions Prayers', slug: 'special-intentions-prayers', count: 3 },
    { name: 'Spiritual Life Prayers', slug: 'spiritual-life-prayers', count: 5 },
    { name: 'St. Anthony of Padua Prayers', slug: 'st-anthony-of-padua-prayers', count: 22 },
    { name: 'St. Gregory the Great Prayers', slug: 'st-gregory-the-great-prayers', count: 1 },
    { name: 'St. Joseph Prayers', slug: 'st-joseph-prayers', count: 25 },
    { name: 'St. Patrick Prayers', slug: 'st-patrick-prayers', count: 10 },
    { name: 'St. Valentine Prayers', slug: 'st-valentine-prayers', count: 15 },
    { name: 'Stewardship Prayers', slug: 'stewardship-prayers', count: 2 },
    { name: 'Strength Prayers', slug: 'strength-prayers', count: 3 },
    { name: 'Study Prayers', slug: 'study-prayers', count: 5 },
    { name: 'Thanks Prayers', slug: 'thanks-prayers', count: 1 },
    { name: 'The Rosary in Croatian', slug: 'the-rosary-in-croatian-prayers', count: 1 },
    { name: 'The Rosary in Dutch', slug: 'the-rosary-in-dutch-prayers', count: 1 },
    { name: 'The Rosary in English', slug: 'the-rosary-in-english-prayers', count: 5 },
    { name: 'The Rosary in French', slug: 'the-rosary-in-french-prayers', count: 1 },
    { name: 'The Rosary in German', slug: 'the-rosary-in-german-prayers', count: 1 },
    { name: 'The Rosary in Irish-Gaelic', slug: 'the-rosary-in-irish-gaelic-prayers', count: 1 },
    { name: 'The Rosary in Italian', slug: 'the-rosary-in-italian-prayers', count: 1 },
    { name: 'The Rosary in Latin', slug: 'the-rosary-in-latin-prayers', count: 1 },
    { name: 'The Rosary in Polish', slug: 'the-rosary-in-polish-prayers', count: 1 },
    { name: 'Travel Prayers', slug: 'travel-prayers', count: 8 },
    { name: 'Trust Prayers', slug: 'trust-prayers', count: 2 },
    { name: 'Unity Prayers', slug: 'unity-prayers', count: 12 },
    { name: 'Virtue Prayers', slug: 'virtue-prayers', count: 4 },
    { name: 'Vocation Prayers', slug: 'vocation-prayers', count: 12 },
    { name: 'Wedding Prayers', slug: 'wedding-prayers', count: 4 },
    { name: 'Wisdom Prayers', slug: 'wisdom-prayers', count: 2 },
];

// ============================================================================
// MAIN SEED FUNCTION
// ============================================================================
async function main() {
    console.log('🌱 Importing all 385 categories from myprayertower.com...');
    console.log('');

    let categoryCount = 0;

    // Create all categories
    for (let i = 0; i < allCategories.length; i++) {
        const cat = allCategories[i];
        try {
            await prisma.prayerLibraryCategory.upsert({
                where: { slug: cat.slug },
                create: {
                    name: cat.name,
                    slug: cat.slug,
                    description: `${cat.count} prayers in this category`,
                    sortOrder: i + 1,
                },
                update: {
                    name: cat.name,
                    description: `${cat.count} prayers in this category`,
                },
            });
            categoryCount++;
        } catch (error: any) {
            // Skip duplicates
        }

        // Progress update every 50
        if (categoryCount % 50 === 0 && categoryCount > 0) {
            console.log(`Progress: ${categoryCount} categories imported...`);
        }
    }

    console.log('');
    console.log('🎉 ========================================');
    console.log('🎉 IMPORT COMPLETED!');
    console.log('🎉 ========================================');
    console.log(`📁 Categories imported: ${categoryCount}`);
    console.log('');
    console.log('The categories now match your production myprayertower.com site!');
}

main()
    .catch((e) => {
        console.error('❌ Seed failed:', e);
        process.exit(1);
    })
    .finally(() => prisma.$disconnect());
